
(()=>{"use strict";
const K="bahnasawi_coffee_erp_v1",S=8;
const st={d:{products:[],agents:[],orders:[],returns:[],payments:[],inventoryMoves:[]},u:{p:"dashboard",pp:1,ap:1,items:[],f:{from:"",to:"",agentId:"all"}},c:{top:null,ag:null,flow:null}},el={};
const U={id:()=>`${Date.now()}_${Math.random().toString(16).slice(2)}`,
m:n=>Number(n||0).toLocaleString("en-US",{minimumFractionDigits:2,maximumFractionDigits:2}),
q:n=>Number(n||0).toLocaleString("en-US",{minimumFractionDigits:2,maximumFractionDigits:2}),
d:d=>String(d||"").slice(0,10),t:()=>new Date().toISOString().slice(0,10),
e:s=>String(s||"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]))};
const DB={load(){const r=localStorage.getItem(K);if(!r)return;try{const p=JSON.parse(r),pro=(p.products||[]).map(x=>({...x,openingStock:+(x.openingStock||0),currentStock:+(x.currentStock??x.openingStock??0)}));st.d={products:pro,agents:p.agents||[],orders:p.orders||[],returns:p.returns||[],payments:p.payments||[],inventoryMoves:p.inventoryMoves||[]};}catch{}},save(){localStorage.setItem(K,JSON.stringify(st.d));},clear(){localStorage.removeItem(K);st.d={products:[],agents:[],orders:[],returns:[],payments:[],inventoryMoves:[]};}};
const C={agt(id){const o=st.d.orders.filter(x=>x.agentId===id).reduce((a,b)=>a+ +b.total,0),r=st.d.returns.filter(x=>x.agentId===id).reduce((a,b)=>a+ +b.total,0),p=st.d.payments.filter(x=>x.agentId===id).reduce((a,b)=>a+ +b.amount,0);return{out:o,ret:r,paid:p,bal:o-r-p};},stats(){const tp=st.d.products.length,ta=st.d.agents.length,ts=st.d.products.reduce((a,p)=>a+ +p.currentStock,0),td=st.d.agents.reduce((a,g)=>a+Math.max(0,this.agt(g.id).bal),0),tv=st.d.orders.reduce((a,o)=>a+ +o.total,0);return{tp,ta,ts,td,tv};},fd(rows,key="date"){const{from,to}=st.u.f;return rows.filter(r=>{const d=String(r[key]||"").slice(0,10);if(from&&d<from)return false;if(to&&d>to)return false;return true;});}};
const UI={cache(){el.nav=document.querySelectorAll(".nav-btn");el.pages=document.querySelectorAll(".page");
["statsGrid","loader","modalRoot","toastContainer","addProductBtn","productSearch","productsTableBody","productsPagination","inventoryTableBody","addAgentBtn","agentSearch","agentsTableBody","agentsPagination","orderAgentSelect","orderDate","orderItemsContainer","addOrderItemBtn","orderTotal","saveOrderBtn","returnAgentSelect","returnProductSelect","returnQty","returnValue","returnDate","saveReturnBtn","reportFromDate","reportToDate","reportAgentSelect","applyReportFilters","agentsReportBody","warehouseReportBody","stockReportBody","topProductsReportBody","profitReportBody","exportDataBtn","importDataInput","clearDataBtn","printCurrentPage"].forEach(i=>el[i]=document.getElementById(i));el.rActions=document.querySelectorAll(".report-actions");},
toast(m,t="success"){const x=document.createElement("div");x.className=`toast ${t}`;x.textContent=m;el.toastContainer.appendChild(x);setTimeout(()=>x.remove(),3000);},
sw(p){st.u.p=p;el.nav.forEach(b=>b.classList.toggle("active",b.dataset.page===p));el.pages.forEach(g=>g.classList.toggle("active",g.id===`page-${p}`));},
modal({title,fields,onSubmit,submitText="حفظ"}){el.modalRoot.innerHTML=`<div class="modal-overlay"><div class="modal"><div class="modal-head"><h3>${U.e(title)}</h3><button class="btn ghost" data-c>إغلاق</button></div><form id="mf"><div class="grid-2">${fields.map(f=>`<div><label>${U.e(f.label)}</label><input id="m_${f.name}" type="${f.type||"text"}" value="${U.e(f.value||"")}" ${f.readonly?"readonly":""}></div>`).join("")}</div><div style="margin-top:12px;display:flex;gap:8px"><button class="btn primary" type="submit">${U.e(submitText)}</button><button class="btn ghost" type="button" data-c>إلغاء</button></div></form></div></div>`;const cls=()=>el.modalRoot.innerHTML="";el.modalRoot.querySelectorAll("[data-c]").forEach(b=>b.onclick=cls);document.getElementById("mf").onsubmit=e=>{e.preventDefault();const v={};fields.forEach(f=>v[f.name]=document.getElementById(`m_${f.name}`).value.trim());onSubmit(v,cls);};},cf:m=>confirm(m)};
const Pg={slice(r,p){const t=Math.max(1,Math.ceil(r.length/S)),sp=Math.min(Math.max(1,p),t),s=(sp-1)*S;return{t,sp,d:r.slice(s,s+S)};},draw(c,t,p,h){c.innerHTML="";for(let i=1;i<=t;i++){const b=document.createElement("button");b.className=`page-btn ${i===p?"active":""}`;b.textContent=i;b.onclick=()=>h(i);c.appendChild(b);}}};
const P={add(){UI.modal({title:"إضافة منتج",fields:[{name:"name",label:"اسم المنتج"},{name:"price",label:"سعر البيع",type:"number"}],onSubmit:(v,cl)=>{if(!v.name||+v.price<=0)return UI.toast("تحقق من البيانات","error");const p={id:U.id(),name:v.name,price:+v.price,openingStock:0,currentStock:0,createdAt:new Date().toISOString()};st.d.products.push(p);DB.save();R.all();cl();UI.toast("تمت الإضافة");}});},
edit(id){const p=st.d.products.find(x=>x.id===id);if(!p)return;UI.modal({title:"تعديل المنتج",fields:[{name:"name",label:"الاسم",value:p.name},{name:"price",label:"السعر",type:"number",value:p.price}],onSubmit:(v,cl)=>{if(!v.name||+v.price<=0)return UI.toast("تحقق من البيانات","error");p.name=v.name;p.price=+v.price;DB.save();R.all();cl();UI.toast("تم التعديل");}});},
del(id){if(!UI.cf("حذف المنتج؟"))return;st.d.products=st.d.products.filter(x=>x.id!==id);DB.save();R.all();UI.toast("تم الحذف","info");}};
const Inv={setOpen(id){const p=st.d.products.find(x=>x.id===id),inp=document.querySelector(`[data-open-input='${id}']`);if(!p||!inp)return;const v=+inp.value||0;if(v<0)return UI.toast("رصيد أول المدة غير صحيح","error");const diff=v-(+p.openingStock||0);p.openingStock=v;p.currentStock=(+p.currentStock||0)+diff;if(diff!==0)st.d.inventoryMoves.push({id:U.id(),type:"in",productId:id,qty:Math.abs(diff),value:Math.abs(diff)*+p.price,date:U.t(),ref:"opening"});DB.save();R.all();UI.toast("تم حفظ رصيد أول المدة");},addFactory(id){const p=st.d.products.find(x=>x.id===id),inp=document.querySelector(`[data-factory-input='${id}']`);if(!p||!inp)return;const q=+inp.value||0;if(q<=0)return UI.toast("أدخل كمية وارد صحيحة","error");p.currentStock=(+p.currentStock||0)+q;st.d.inventoryMoves.push({id:U.id(),type:"in",productId:id,qty:q,value:q*+p.price,date:U.t(),ref:"factory"});DB.save();R.all();UI.toast("تمت إضافة الوارد من المصنع");}};
const A={add(){UI.modal({title:"إضافة مندوب",fields:[{name:"name",label:"اسم المندوب"},{name:"phone",label:"رقم الهاتف"},{name:"vehicle",label:"العربية"}],onSubmit:(v,cl)=>{if(!v.name)return UI.toast("الاسم مطلوب","error");st.d.agents.push({id:U.id(),name:v.name,phone:v.phone,vehicle:v.vehicle,createdAt:new Date().toISOString()});DB.save();R.all();cl();UI.toast("تمت الإضافة");}});},
edit(id){const a=st.d.agents.find(x=>x.id===id);if(!a)return;UI.modal({title:"تعديل المندوب",fields:[{name:"name",label:"الاسم",value:a.name},{name:"phone",label:"الهاتف",value:a.phone},{name:"vehicle",label:"العربية",value:a.vehicle}],onSubmit:(v,cl)=>{if(!v.name)return UI.toast("الاسم مطلوب","error");a.name=v.name;a.phone=v.phone;a.vehicle=v.vehicle;DB.save();R.all();cl();UI.toast("تم التعديل");}});},
pay(id){const a=st.d.agents.find(x=>x.id===id);if(!a)return;UI.modal({title:`تسجيل سداد - ${a.name}`,fields:[{name:"amount",label:"المبلغ",type:"number"},{name:"date",label:"التاريخ",type:"date",value:U.t()},{name:"note",label:"ملاحظة"}],onSubmit:(v,cl)=>{if(+v.amount<=0||!v.date)return UI.toast("تحقق من السداد","error");st.d.payments.push({id:U.id(),agentId:id,amount:+v.amount,date:v.date,note:v.note||""});DB.save();R.all();cl();UI.toast("تم تسجيل السداد");}});},
del(id){if(!UI.cf("حذف المندوب؟"))return;st.d.agents=st.d.agents.filter(x=>x.id!==id);DB.save();R.all();UI.toast("تم الحذف","info");}};
const O={reset(){st.u.items=[];el.orderDate.value=U.t();this.add();this.ri();this.ut();},add(){st.u.items.push({productId:"",qty:0,price:0,total:0});},rem(i){st.u.items.splice(i,1);if(!st.u.items.length)this.add();this.ri();this.ut();},ri(){el.orderItemsContainer.innerHTML=st.u.items.map((it,i)=>`<div class="order-item" data-i="${i}"><div class="grid-3"><div><label>المنتج</label><select class="op"><option value="">اختر المنتج</option>${st.d.products.map(p=>`<option value="${p.id}" ${it.productId===p.id?"selected":""}>${U.e(p.name)}</option>`).join("")}</select></div><div><label>الكمية</label><input class="oq" type="number" step="0.01" value="${it.qty||""}"></div><div><label>السعر</label><input class="os" type="number" value="${it.price}" readonly></div></div><div style="display:flex;justify-content:space-between;margin-top:8px"><span>إجمالي الصنف: <strong class="ot">${U.m(it.total)}</strong> جنيه</span><button class="btn danger od" type="button">حذف</button></div></div>`).join("");
el.orderItemsContainer.querySelectorAll(".order-item").forEach(c=>{const i=+c.dataset.i;c.querySelector(".op").onchange=e=>{const p=st.d.products.find(x=>x.id===e.target.value);st.u.items[i].productId=e.target.value;st.u.items[i].price=p?+p.price:0;this.rc(i);this.ri();};c.querySelector(".oq").oninput=e=>{st.u.items[i].qty=+e.target.value||0;this.rc(i);c.querySelector(".ot").textContent=U.m(st.u.items[i].total);};c.querySelector(".od").onclick=()=>this.rem(i);});},rc(i){const x=st.u.items[i];x.total=(+x.qty||0)*(+x.price||0);this.ut();},ut(){el.orderTotal.textContent=U.m(st.u.items.reduce((a,b)=>a+ +b.total,0));},
save(){const aid=el.orderAgentSelect.value,date=el.orderDate.value;if(!aid||!date)return UI.toast("اختر المندوب والتاريخ","error");const items=st.u.items.filter(i=>i.productId&&i.qty>0);if(!items.length)return UI.toast("أضف صنفًا صحيحًا","error");for(const i of items){const p=st.d.products.find(x=>x.id===i.productId);if(!p||+p.currentStock<+i.qty)return UI.toast(`رصيد غير كاف: ${p?p.name:"منتج"}`,"error");}
items.forEach(i=>{const p=st.d.products.find(x=>x.id===i.productId);p.currentStock=+p.currentStock-+i.qty;st.d.inventoryMoves.push({id:U.id(),type:"out",productId:p.id,qty:+i.qty,value:+i.total,date,ref:"order"});});
const total=items.reduce((a,b)=>a+ +b.total,0);st.d.orders.push({id:U.id(),agentId:aid,date,items,total});DB.save();this.reset();R.all();UI.toast("تم حفظ الطلبية");}};
const Rt={bind(){const f=()=>{const p=st.d.products.find(x=>x.id===el.returnProductSelect.value),q=+el.returnQty.value||0;el.returnValue.value=p?(q*+p.price).toFixed(2):"0.00";};el.returnProductSelect.onchange=f;el.returnQty.oninput=f;},save(){const aid=el.returnAgentSelect.value,pid=el.returnProductSelect.value,q=+el.returnQty.value||0,d=el.returnDate.value,p=st.d.products.find(x=>x.id===pid);if(!aid||!pid||q<=0||!d||!p)return UI.toast("تحقق من البيانات","error");const tot=q*+p.price;p.currentStock=+p.currentStock+q;st.d.returns.push({id:U.id(),agentId:aid,productId:pid,qty:q,price:+p.price,total:tot,date:d});st.d.inventoryMoves.push({id:U.id(),type:"return",productId:pid,qty:q,value:tot,date:d,ref:"return"});DB.save();el.returnQty.value="";el.returnValue.value="0.00";R.all();UI.toast("تم تسجيل المرتجع");}};
const PdfAR={font:null,async loadFont(){if(this.font)return this.font;try{const res=await fetch("https://cdn.jsdelivr.net/gh/alif-type/amiri@master/Amiri-Regular.ttf"),buf=await res.arrayBuffer(),bytes=new Uint8Array(buf);let bin="";for(let i=0;i<bytes.length;i+=32768){bin+=String.fromCharCode.apply(null,bytes.subarray(i,i+32768));}const b64=btoa(bin);this.font=b64;return b64;}catch{return null;}},lines(k){if(k==="agents")return Rp.aRows().map(r=>`مندوب: ${r.agent} | المسحوبات: ${U.m(r.out)} | المرتجعات: ${U.m(r.ret)} | المدفوع: ${U.m(r.paid)} | الرصيد: ${U.m(r.bal)}`);if(k==="warehouse")return Rp.wRows().map(r=>`التاريخ: ${r.date} | المنتج: ${r.product} | النوع: ${r.type} | الكمية: ${U.q(r.qty)} | القيمة: ${U.m(r.value)}`);if(k==="stock")return Rp.sRows().map(r=>`المنتج: ${r.product} | الرصيد: ${U.q(r.stock)} | السعر: ${U.m(r.price)} | القيمة: ${U.m(r.value)}`);if(k==="topProducts")return Rp.tRows().map(r=>`المنتج: ${r.product} | الكمية: ${U.q(r.qty)} | القيمة: ${U.m(r.value)}`);return Rp.pRows().map(r=>`${r.title}: ${U.m(r.amount)}`);}};
const Rp={setF(){st.u.f.from=el.reportFromDate.value;st.u.f.to=el.reportToDate.value;st.u.f.agentId=el.reportAgentSelect.value;this.render();},title(k){const m={agents:"تقرير المناديب",warehouse:"تقرير حركة المخزن",stock:"تقرير المخزون",topProducts:"تقرير أكثر المنتجات مبيعًا",profit:"تقرير إجمالي الأرباح"};return m[k]||"تقرير";},aRows(){let g=st.d.agents;if(st.u.f.agentId!=="all")g=g.filter(a=>a.id===st.u.f.agentId);return g.map(a=>{const t=C.agt(a.id);return{agent:a.name,out:t.out,ret:t.ret,paid:t.paid,bal:t.bal,status:t.bal>0?"عليه عجز":t.bal<0?"له رصيد دائن":"حسابه صفر"};});},wRows(){return C.fd(st.d.inventoryMoves).map(m=>{const p=st.d.products.find(x=>x.id===m.productId),tp=m.type==="in"?(m.ref==="opening"?"أول المدة":m.ref==="factory"?"وارد مصنع":"وارد"):m.type==="out"?"منصرف":"مرتجع";return{date:m.date,product:p?p.name:"-",type:tp,qty:m.qty,value:m.value};});},sRows(){return st.d.products.map(p=>({product:p.name,price:p.price,stock:p.currentStock,value:+p.currentStock*+p.price}));},tRows(){const mp={};st.d.orders.forEach(o=>{if(!C.fd([o])[0])return;o.items.forEach(i=>{mp[i.productId]=mp[i.productId]||{qty:0,value:0};mp[i.productId].qty+=+i.qty;mp[i.productId].value+=+i.total;});});return Object.entries(mp).map(([id,v])=>{const p=st.d.products.find(x=>x.id===id);return{product:p?p.name:"-",qty:v.qty,value:v.value};}).sort((a,b)=>b.qty-a.qty);},pRows(){const o=C.fd(st.d.orders).reduce((a,b)=>a+ +b.total,0),r=C.fd(st.d.returns).reduce((a,b)=>a+ +b.total,0);return[{title:"إجمالي المبيعات",amount:o},{title:"إجمالي المرتجعات",amount:r},{title:"صافي الإيراد",amount:o-r}];},
render(){const a=this.aRows(),w=this.wRows(),s=this.sRows(),t=this.tRows(),p=this.pRows();el.agentsReportBody.innerHTML=`<table><thead><tr><th>المندوب</th><th>المسحوبات</th><th>المرتجعات</th><th>المدفوع</th><th>الرصيد</th><th>الحالة</th></tr></thead><tbody>${a.map(r=>`<tr><td>${U.e(r.agent)}</td><td>${U.m(r.out)}</td><td>${U.m(r.ret)}</td><td>${U.m(r.paid)}</td><td>${U.m(r.bal)}</td><td>${r.status}</td></tr>`).join("")||"<tr><td colspan='6'>لا توجد بيانات</td></tr>"}</tbody></table>`;
el.warehouseReportBody.innerHTML=`<table><thead><tr><th>التاريخ</th><th>المنتج</th><th>النوع</th><th>الكمية</th><th>القيمة</th></tr></thead><tbody>${w.map(r=>`<tr><td>${U.d(r.date)}</td><td>${U.e(r.product)}</td><td>${r.type}</td><td>${U.q(r.qty)}</td><td>${U.m(r.value)}</td></tr>`).join("")||"<tr><td colspan='5'>لا توجد بيانات</td></tr>"}</tbody></table>`;
el.stockReportBody.innerHTML=`<table><thead><tr><th>المنتج</th><th>السعر</th><th>الرصيد</th><th>القيمة</th></tr></thead><tbody>${s.map(r=>`<tr><td>${U.e(r.product)}</td><td>${U.m(r.price)}</td><td>${U.q(r.stock)}</td><td>${U.m(r.value)}</td></tr>`).join("")||"<tr><td colspan='4'>لا توجد بيانات</td></tr>"}</tbody></table>`;
el.topProductsReportBody.innerHTML=`<table><thead><tr><th>المنتج</th><th>الكمية</th><th>القيمة</th></tr></thead><tbody>${t.map(r=>`<tr><td>${U.e(r.product)}</td><td>${U.q(r.qty)}</td><td>${U.m(r.value)}</td></tr>`).join("")||"<tr><td colspan='3'>لا توجد بيانات</td></tr>"}</tbody></table>`;
el.profitReportBody.innerHTML=`<table><thead><tr><th>البند</th><th>القيمة</th></tr></thead><tbody>${p.map(r=>`<tr><td>${r.title}</td><td>${U.m(r.amount)}</td></tr>`).join("")}</tbody></table>`;},
print(k){const m={agents:el.agentsReportBody,warehouse:el.warehouseReportBody,stock:el.stockReportBody,topProducts:el.topProductsReportBody,profit:el.profitReportBody},t=m[k];if(!t)return;const w=window.open("","_blank","width=900,height=700"),rt=this.title(k);w.document.write(`<html dir='rtl' lang='ar'><head><meta charset='UTF-8'><style>body{font-family:Cairo,sans-serif;padding:20px}h2{text-align:center}img{width:80px;height:80px;display:block;margin:auto;border-radius:50%}table{width:100%;border-collapse:collapse;margin-top:12px}th,td{border:1px solid #ccc;padding:8px;text-align:right}</style></head><body><img src='789.jpg'><h2>مصنع بن البهنساوي - ${rt}</h2>${t.innerHTML}</body></html>`);w.document.close();w.focus();w.print();},
excel(k){if(typeof XLSX==="undefined")return UI.toast("مكتبة Excel غير متاحة","error");const m={agents:this.aRows().map(r=>({المندوب:r.agent,المسحوبات:r.out,المرتجعات:r.ret,المدفوع:r.paid,الرصيد:r.bal,الحالة:r.status})),warehouse:this.wRows().map(r=>({التاريخ:r.date,المنتج:r.product,النوع:r.type,الكمية:r.qty,القيمة:r.value})),stock:this.sRows().map(r=>({المنتج:r.product,السعر:r.price,الرصيد:r.stock,القيمة:r.value})),topProducts:this.tRows().map(r=>({المنتج:r.product,الكمية:r.qty,القيمة:r.value})),profit:this.pRows().map(r=>({البند:r.title,القيمة:r.amount}))};const wb=XLSX.utils.book_new(),ws=XLSX.utils.json_to_sheet(m[k]||[]);XLSX.utils.book_append_sheet(wb,ws,"Report");XLSX.writeFile(wb,`report_${k}_${Date.now()}.xlsx`);UI.toast("تم تحميل Excel");},
async pdf(k){if(!window.jspdf||!window.jspdf.jsPDF)return UI.toast("مكتبة PDF غير متاحة","error");const{jsPDF}=window.jspdf,doc=new jsPDF({orientation:"p",unit:"mm",format:"a4"}),font=await PdfAR.loadFont();if(font){doc.addFileToVFS("Amiri-Regular.ttf",font);doc.addFont("Amiri-Regular.ttf","Amiri","normal");doc.setFont("Amiri","normal");}else{doc.setFont("helvetica","normal");}doc.setFontSize(16);doc.text(`مصنع بن البهنساوي - ${this.title(k)}`,105,16,{align:"center"});doc.setFontSize(12);const lines=PdfAR.lines(k);let y=28;for(const l of lines){if(y>282){doc.addPage();if(font)doc.setFont("Amiri","normal");else doc.setFont("helvetica","normal");y=20;}doc.text(l,195,y,{align:"right"});y+=8;}doc.save(`report_${k}_${Date.now()}.pdf`);UI.toast("تم تحميل PDF");}};
const Ch={draw(){if(typeof Chart==="undefined")return UI.toast("Chart.js غير متاح","info");Object.values(st.c).forEach(c=>c&&c.destroy());const t=Rp.tRows().slice(0,7);st.c.top=new Chart(document.getElementById("topProductsChart"),{type:"bar",data:{labels:t.map(x=>x.product),datasets:[{label:"كمية الصرف",data:t.map(x=>x.qty),backgroundColor:"#8b5a2b"}]},options:{responsive:true}});const an=st.d.agents.map(a=>a.name),df=st.d.agents.map(a=>Math.max(0,C.agt(a.id).bal));st.c.ag=new Chart(document.getElementById("agentsPerformanceChart"),{type:"line",data:{labels:an,datasets:[{label:"العجز",data:df,borderColor:"#c89b3c",backgroundColor:"rgba(200,155,60,.2)",fill:true}]},options:{responsive:true}});const i=st.d.inventoryMoves.filter(m=>m.type==="in").reduce((a,b)=>a+ +b.qty,0),o=st.d.inventoryMoves.filter(m=>m.type==="out").reduce((a,b)=>a+ +b.qty,0),r=st.d.inventoryMoves.filter(m=>m.type==="return").reduce((a,b)=>a+ +b.qty,0);st.c.flow=new Chart(document.getElementById("warehouseFlowChart"),{type:"doughnut",data:{labels:["وارد","منصرف","مرتجع"],datasets:[{data:[i,o,r],backgroundColor:["#4a2b1a","#d39d2a","#7f5539"]}]},options:{responsive:true}});}};
const X={exp(){const b=new Blob([JSON.stringify(st.d,null,2)],{type:"application/json;charset=utf-8"}),u=URL.createObjectURL(b),a=document.createElement("a");a.href=u;a.download=`bahnasawi_backup_${Date.now()}.json`;a.click();URL.revokeObjectURL(u);UI.toast("تم تصدير البيانات");},imp(f){const r=new FileReader();r.onload=()=>{try{const p=JSON.parse(r.result),pro=(p.products||[]).map(x=>({...x,openingStock:+(x.openingStock||0),currentStock:+(x.currentStock??x.openingStock??0)}));st.d={products:pro,agents:p.agents||[],orders:p.orders||[],returns:p.returns||[],payments:p.payments||[],inventoryMoves:p.inventoryMoves||[]};DB.save();R.all();UI.toast("تم استيراد البيانات");}catch{UI.toast("ملف غير صالح","error");}};r.readAsText(f,"UTF-8");}};
const R={stats(){const s=C.stats(),c=[{t:"إجمالي عدد المنتجات",v:s.tp,m:"منتج مسجل",ic:"📦"},{t:"إجمالي عدد المناديب",v:s.ta,m:"مندوب نشط",ic:"🚚"},{t:"إجمالي رصيد المخزن الحالي (عدد)",v:U.q(s.ts),m:"وحدات متاحة",ic:"🏬"},{t:"إجمالي العجز الكلي للمناديب",v:U.m(s.td),m:"رصيد مستحق",ic:"⚠️"},{t:"إجمالي قيمة البضاعة المنصرفة",v:U.m(s.tv),m:"إجمالي حركة الصرف",ic:"💰"}];el.statsGrid.innerHTML=c.map((x,i)=>`<article class='stat-card stat-${i+1}'><div class='stat-top'><h4>${x.t}</h4><span class='stat-icon'>${x.ic}</span></div><p class='stat-value'>${x.v}</p><div class='stat-meta'>${x.m}</div></article>`).join("");},
products(){const q=(el.productSearch.value||"").trim().toLowerCase(),rows=st.d.products.filter(p=>p.name.toLowerCase().includes(q)),p=Pg.slice(rows,st.u.pp);st.u.pp=p.sp;el.productsTableBody.innerHTML=p.d.map(x=>`<tr><td>${U.e(x.name)}</td><td>${U.m(x.price)}</td><td>${U.q(x.currentStock)}</td><td><button class='btn ghost' data-pe='${x.id}'>تعديل</button><button class='btn danger' data-pd='${x.id}'>حذف</button></td></tr>`).join("")||"<tr><td colspan='4'>لا توجد منتجات</td></tr>";Pg.draw(el.productsPagination,p.t,p.sp,n=>{st.u.pp=n;this.products();B.dyn();});},
agents(){const q=(el.agentSearch.value||"").trim().toLowerCase(),rows=st.d.agents.filter(a=>a.name.toLowerCase().includes(q)),p=Pg.slice(rows,st.u.ap);st.u.ap=p.sp;el.agentsTableBody.innerHTML=p.d.map(x=>{const t=C.agt(x.id),s=t.bal>0?"مدين":t.bal<0?"دائن":"صفر";return`<tr><td>${U.e(x.name)}</td><td>${U.e(x.phone||"-")}</td><td>${U.e(x.vehicle||"-")}</td><td>${s} (${U.m(t.bal)})</td><td><button class='btn ghost' data-ae='${x.id}'>تعديل</button><button class='btn secondary' data-ap='${x.id}'>سداد</button><button class='btn danger' data-ad='${x.id}'>حذف</button></td></tr>`;}).join("")||"<tr><td colspan='5'>لا توجد مناديب</td></tr>";Pg.draw(el.agentsPagination,p.t,p.sp,n=>{st.u.ap=n;this.agents();B.dyn();});},
inventory(){if(!el.inventoryTableBody)return;el.inventoryTableBody.innerHTML=st.d.products.map(p=>`<tr><td>${U.e(p.name)}</td><td><input type='number' min='0' step='0.01' value='${+p.openingStock||0}' data-open-input='${p.id}'></td><td>${U.q(p.currentStock)}</td><td><input type='number' min='0' step='0.01' value='' placeholder='كمية وارد' data-factory-input='${p.id}'></td><td><button class='btn secondary' data-inv-open='${p.id}'>حفظ أول المدة</button> <button class='btn primary' data-inv-in='${p.id}'>إضافة وارد</button></td></tr>`).join("")||"<tr><td colspan='5'>لا توجد منتجات</td></tr>";},
sel(){const a=["<option value=''>اختر المندوب</option>"].concat(st.d.agents.map(g=>`<option value='${g.id}'>${U.e(g.name)}</option>`)).join("");el.orderAgentSelect.innerHTML=a;el.returnAgentSelect.innerHTML=a;el.reportAgentSelect.innerHTML=["<option value='all'>كل المناديب</option>"].concat(st.d.agents.map(g=>`<option value='${g.id}'>${U.e(g.name)}</option>`)).join("");el.returnProductSelect.innerHTML=["<option value=''>اختر المنتج</option>"].concat(st.d.products.map(p=>`<option value='${p.id}'>${U.e(p.name)}</option>`)).join("");if(!st.u.items.length)O.add();O.ri();},
all(){this.stats();this.products();this.inventory();this.agents();this.sel();Rp.render();Ch.draw();B.dyn();}};
const B={stat(){el.nav.forEach(b=>b.onclick=()=>UI.sw(b.dataset.page));el.addProductBtn.onclick=()=>P.add();el.productSearch.oninput=()=>{st.u.pp=1;R.products();B.dyn();};el.addAgentBtn.onclick=()=>A.add();el.agentSearch.oninput=()=>{st.u.ap=1;R.agents();B.dyn();};el.addOrderItemBtn.onclick=()=>{O.add();O.ri();};el.saveOrderBtn.onclick=()=>O.save();el.saveReturnBtn.onclick=()=>Rt.save();Rt.bind();el.orderDate.value=U.t();el.returnDate.value=U.t();el.applyReportFilters.onclick=()=>Rp.setF();el.rActions.forEach(w=>{const k=w.dataset.report;w.querySelector(".report-print").onclick=()=>Rp.print(k);w.querySelector(".report-excel").onclick=()=>Rp.excel(k);w.querySelector(".report-pdf").onclick=()=>Rp.pdf(k);});el.exportDataBtn.onclick=()=>X.exp();el.importDataInput.onchange=e=>{const f=e.target.files&&e.target.files[0];if(f)X.imp(f);e.target.value="";};el.clearDataBtn.onclick=()=>{if(!UI.cf("سيتم حذف جميع البيانات نهائيًا. متابعة؟"))return;DB.clear();O.reset();R.all();UI.toast("تم حذف جميع البيانات","info");};el.printCurrentPage.onclick=()=>print();},
dyn(){document.querySelectorAll("[data-pe]").forEach(b=>b.onclick=()=>P.edit(b.dataset.pe));document.querySelectorAll("[data-pd]").forEach(b=>b.onclick=()=>P.del(b.dataset.pd));document.querySelectorAll("[data-ae]").forEach(b=>b.onclick=()=>A.edit(b.dataset.ae));document.querySelectorAll("[data-ap]").forEach(b=>b.onclick=()=>A.pay(b.dataset.ap));document.querySelectorAll("[data-ad]").forEach(b=>b.onclick=()=>A.del(b.dataset.ad));document.querySelectorAll("[data-inv-open]").forEach(b=>b.onclick=()=>Inv.setOpen(b.dataset.invOpen));document.querySelectorAll("[data-inv-in]").forEach(b=>b.onclick=()=>Inv.addFactory(b.dataset.invIn));}};
function init(){UI.cache();DB.load();B.stat();O.reset();R.all();setTimeout(()=>el.loader.style.display="none",500);}window.addEventListener("DOMContentLoaded",init);
})();

